// Code generated by "stringer -type SpecializationType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpecNone-0]
	_ = x[SpecIndexGetter-1]
	_ = x[SpecIndexSetter-2]
	_ = x[SpecKeyGetter-3]
	_ = x[SpecKeySetter-4]
	_ = x[SpecKeyDeleter-5]
}

const _SpecializationType_name = "SpecNoneSpecIndexGetterSpecIndexSetterSpecKeyGetterSpecKeySetterSpecKeyDeleter"

var _SpecializationType_index = [...]uint8{0, 8, 23, 38, 51, 64, 78}

func (i SpecializationType) String() string {
	if i < 0 || i >= SpecializationType(len(_SpecializationType_index)-1) {
		return "SpecializationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SpecializationType_name[_SpecializationType_index[i]:_SpecializationType_index[i+1]]
}
