// Code generated by "stringer -type=tokenType -trimprefix=tokenType"; DO NOT EDIT.

package parser

import "strconv"

const _tokenType_name = "ErrorEOFWhitespaceCommentKeywordIdentifierNumberLeftBraceRightBraceLeftParenRightParenLeftBracketRightBracketLeftTriRightTriEqualsSemicolonCommaQuestionMarkColonVariadic"

var _tokenType_index = [...]uint8{0, 5, 8, 18, 25, 32, 42, 48, 57, 67, 76, 86, 97, 109, 116, 124, 130, 139, 144, 156, 161, 169}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
